### ISSUE TITLE
mariadb error with older docker versions

### ISSUE THREAD

**Issue by tobiasfaust** [lapicidae/mariadb-epglv#5]
Hi,
its possible to override the basimage by docker-compose yaml or change the baseimage in dockerfile?
mariadb:latest is not possible to start with docker < version 20.x

please refer: https://github.com/MariaDB/mariadb-docker/issues/434

**Comment by lapicidae** [comment]
Now I'm back from vacation :-)

I will look into it and then possibly create an alternative image/dockerfile.

**Comment by lapicidae** [comment]
It should now be possible to change the base image version via the "VERSION_TAG" build-arg.

Example:
`docker build --tag mariadb-epglv --build-arg VERSION_TAG=10.7 .`

**Comment by tobiasfaust** [comment]
It works :)
thanks

<code>
db:

    image: mariadb-epglv
    build:
      context: https://github.com/lapicidae/mariadb-epglv.git
      args:
        - VERSION_TAG=10.8.2
    container_name: mariadb-epglv
    volumes:
      - db_data:/var/lib/mysql:rw
      - var_run:/run/mysqld:rw
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - LANG=de_DE.UTF-8
      - EPGD_RECOMMEND=yes
      - TZ=Europe/Berlin
    command: mysqld
    entrypoint: /mariadb-epglv.sh
    network_mode: bridge
    ports:
      - '3306:3306'
    restart: unless-stopped
</code>
